### ISSUE TITLE
Clicking on trains in the sidebar doesn't do anything

### ISSUE THREAD

**Issue by calliecameron** [Zhincore/dynmap-trains#13]
Clicking on the name of a train in the sidebar gives the error:

```
Uncaught Cannot select map null map.js:479:15
    selectMapAndPan map.js:479
    RenderManager trains.js:741
    jQuery 8
    RenderManager trains.js:737
    #onMessage trains.js:235
    <anonymous> trains.js:213
    (Async: EventHandlerNonNull)
    connect trains.js:212
    connect trains.js:790
    (Async: promise callback)
    connect trains.js:790
    onAdd trains.js:846
    fire Events.js:203
    _layerAdd Layer.js:116
    whenReady Map.js:1470
    addLayer Layer.js:172
    trains trains.js:860
    initialize map.js:361
    each jQuery
    initialize map.js:360
    onload dynmaputils.js:277
    (Async: EventHandlerNonNull)
    loadjs dynmaputils.js:274
    initialize map.js:357
    each jQuery
    initialize map.js:355
    DynMap map.js:38
    jQuery 10
    DynMap map.js:28
    <anonymous> (index):49
    jQuery 13
```

Should it be focusing on the train like clicking on a player in the sidebar does?

Happens for any train that shows up, whether on the rails or derailed during the current session.

**Comment by joshhunt** [comment]
I believe this is due to the map name being non-standard (not "world") and either not having a mapping in the config, or the default value remaining.

To fix, in the [configuration](https://github.com/Zhincore/dynmap-trains?tab=readme-ov-file#configuration), make sure you create the `worlds` mapping, and unset the default `world`, like:

```yaml
  - class: org.dynmap.ClientComponent
    type: trains
    base-url: "example.com"
    worlds:
      world: "blah-dummy-value"
      "First Adventure": "minecraft:overworld"
      DIM-1: "minecraft:the_nether"
      DIM1:  "minecraft:the_end"
```

However, even after doing this I notice that it'll only switch dimensions. It won't pan the map to focus on the train.
