### ISSUE TITLE
Issues getting it to work

### ISSUE THREAD

**Issue by zwirth2795** [Zhincore/dynmap-trains#5]
I'm not sure why, but I cannot seem to get the map to render the info from CTM. I do not have a link for any of the maps. Does it accept the public IP and port for the `base-url`?

**Comment by ST-DDT** [comment]
Besides having the baseUrl setup you also need the world mapping. This could be explained a little bit better.

Also a trouble shooting guide would be good:
- Check F12/network console, for failing requests to the CTM API 
  (the requests should still be running e.g. `http://my-server.com:3876/api/trains.rt`, sadly we are unable to view the contents of it unless we use `curl`)
- Check world name mapping in `dynmap/configurations.txt` -> `components` between 
  - `dynmap/worlds.txt` (if empty run `/dmap worldset <worldname> enabled:true`) 
  - you can also use `server.properties` -> `level-name=<worldname>`
  - vs `config/create-track-map.json`

So the min dynmap config basically looks like this:

````yaml
  - class: org.dynmap.ClientComponent
    type: trains
    base-url: "http://my-server.com:3876"
    worlds:
      "worldname": "minecraft:overworld"
      DIM-1: "minecraft:the_nether"
      DIM1:  "minecraft:the_end"
````
