### ISSUE TITLE
Trains not showing on dynmap

### ISSUE THREAD

**Issue by SamEmam** [Zhincore/dynmap-trains#7]
Dynmap loads with all tracks and stations, but trains do not show up.

![image](https://github.com/Zhincore/dynmap-trains/assets/22442460/d4ff47d3-be2a-4c7a-a818-ec596d19ecab)

Trains show up just fine on Create Track Map

![image](https://github.com/Zhincore/dynmap-trains/assets/22442460/5d373816-f470-4148-aee6-45f961918ebe)

No issues detected in network log.

**Versions in use:**
- **Server**: Forge 1.20.1
- **Create**: 0.5.1
- **CTM**: NeoForge 1.4
- **Dynmap-trains**: 1.2

Here is my addition to the dynmap `configuration.txt`

```YAML
components:
  - class: org.dynmap.ClientComponent
    type: trains
    base-url: "http://server_url:track_map_port"
    worlds:
      ohana: "minecraft:overworld"
    # Configuration for each layer
    #   `hidden` - Whether or not should the layer be hidden by default
    #   `label` - The label of the layer to show in the UI
    layers: 
      trains:
        hidden: false
        label: Trains
      blocks:
        hidden: false
        label: Train Tracks
      signals:
        hidden: false
        label: Train Signals
      stations:
        hidden: false
        label: Train Stations
      portals:
        hidden: false
        label: Train Portals
    # Additional texts used in the UI 
    labels: 
      # Tooltip for portal marker 
      portal: "Portal to "
      # Tooltip for station marker 
      station: Station
      # Tooltip whether the station is assembling 
      assembling: Assembling
      # Tooltip for train marker 
      train: Train
      # Owner of train 
      owner: Owner
    # Width of the rectangles representing trains (in blocks) 
    train-width: 3
    # Width of the lines representing tracks 
    track-width: 0.75
    # Width of the outline around the track lines 
    track-outline: 1
    # Whether or not should the track outline visually separate track segments 
    track-separation-outline: true
```
