### ISSUE TITLE
Not working in overworld, zooming glitched in nether.

### ISSUE THREAD

**Issue by Alixollo** [Zhincore/dynmap-trains#8]
It seems tracks dont show up in the overworld and are zoomed somewhat randomly in the nether.

Console looks like this :
![image](https://github.com/Zhincore/dynmap-trains/assets/89808322/00bd23b5-592e-4202-b6d9-0cdda6a6808f)

Running fabric server, configuration is
```
components:
  - class: org.dynmap.ClientConfigurationComponent
  - class: org.dynmap.ClientComponent
    type: trains
    base-url: "http://MYSERVERIP:MYSERVERCTMPORT"
    worlds:
      OWQC_MODDED: "minecraft:overworld"
      DIM-1: "minecraft:the_nether"
      DIM1: "minecraft:the_end"
```
